package main

import (
	"encoding/json"
	"os"
	"testing"
	"time"
)

type goldenFile struct {
	Window int `json:"window"`
	Cases  []struct {
		OffsetMs int64  `json:"offset_ms"`
		Manifest string `json:"manifest"`
	} `json:"cases"`
}

// The Go origin must render byte-for-byte identically to the canonical Python
// renderer. golden.json is generated by scripts/gen_go_fixtures.py; if this
// fails, the Go port has drifted from the Python source of truth.
func TestMatchesPythonGolden(t *testing.T) {
	snap, err := LoadSnapshot("testdata/snapshot.json")
	if err != nil {
		t.Fatalf("load snapshot: %v", err)
	}

	raw, err := os.ReadFile("testdata/golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var golden goldenFile
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(golden.Cases) == 0 {
		t.Fatal("no golden cases")
	}

	for _, c := range golden.Cases {
		nowMicros := snap.epochMicros + c.OffsetMs*1000
		got, err := snap.Render(nowMicros, golden.Window)
		if err != nil {
			t.Fatalf("render at +%dms: %v", c.OffsetMs, err)
		}
		if got != c.Manifest {
			t.Errorf("mismatch at +%dms:\n--- want ---\n%s\n--- got ---\n%s",
				c.OffsetMs, c.Manifest, got)
		}
	}
	t.Logf("verified %d manifests against the Python golden", len(golden.Cases))
}

func TestBeforeEpochIsNotStarted(t *testing.T) {
	snap, err := LoadSnapshot("testdata/snapshot.json")
	if err != nil {
		t.Fatalf("load snapshot: %v", err)
	}
	if _, err := snap.Render(snap.epochMicros-int64(time.Second/time.Microsecond), 6); err != ErrNotStarted {
		t.Fatalf("want ErrNotStarted, got %v", err)
	}
}
